### ISSUE TITLE
Rendering Error

### ISSUE THREAD

**Issue by cloudythoughts06** [XorDev/Trippy-Shaderpack#1]
When I invert the globe shader and look just a _tiny_ bit upwards, a lot of the landscape just stops being visible. This is kind of an issue, as I can't really enjoy the weird trippiness of the inverted globe if everything doesn't stay visible.

Picture 1, what it looks like normally: ![2021-01-17_11 13 05](https://user-images.githubusercontent.com/77581443/104848936-1fc10380-58b5-11eb-8520-e71ccdb1e9d5.png)

Picture 2, after looking slightly upward: ![2021-01-17_11 13 07](https://user-images.githubusercontent.com/77581443/104848953-3ff0c280-58b5-11eb-8451-2c5108518b28.png)

**Comment by XorDev** [comment]
Add this to shaders.properties file.
`frustum.culling = false`

I didn't add this to the release because it slows the rendering, and most people don't use the inverted globe.
